%YAML:1.0

# Camera Parameters. Adjust them!

# Camera calibration parameters (OpenCV) 
Camera.fx: 556.1010372628705
Camera.fy: 555.9708015481489
Camera.cx: 319.6393583856645
Camera.cy: 150.9267437269284

# Camera distortion paremeters (OpenCV) --
Camera.k1: -0.5458885244896164
Camera.k2: 0.3626755666711843
Camera.p1: -0.001791877120302593
Camera.p2: -0.002582045344606729

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
### Changing the parameters below could seriously degradate the performance of the system

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold (lower less restrictive)			
ORBextractor.fastTh: 20

# ORB Extractor: Score to sort features. 0 -> Harris Score, 1 -> FAST Score			
ORBextractor.nScoreType: 1


# Constant Velocity Motion Model (0 - disabled, 1 - enabled [recommended])
UseMotionModel: 1
